services:
  tiptap-app:
    image: ghcr.io/junbyeol/tiptap-app:latest
    container_name: tiptap-app
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true
