services:
  tiptap-app: # resume-app → tiptap-app
    image: ghcr.io/junbyeol/tiptap-app:latest # 이미지명 변경
    container_name: tiptap-app
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true
